apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
    
      imagePullSecrets:
      - name: google-registry
      containers:
      - image: gcr.io/wired-sol-367809/helloworldapp:latest
        name: helloworld
        ports:
        - containerPort: 8000
        resources: {}
        env:
          - name: REDIS_HOST
            value: redis-service

---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld-service
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
  - name: helloworldport
    port: 80
    protocol: TCP
    targetPort: 8000







# kubectl create secret docker-registry google-registry --docker-server=http://gcr.io --docker-username=_json_key --docker-password="$(cat sakey.json)"